apiVersion: istio.openshift.com/v1alpha3
kind: ControlPlane
metadata:
  name: minimal-istio
spec:
  istio:
    global:
      # use community images
      hub: "maistra"
      tag: 0.10.0
      proxy:
        autoInject: disabled
      useMCP: false
      disablePolicyChecks: false
      omitSidecarInjectorConfigMap: true
    galley:
      enabled: false
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
      istio-egressgateway:
        enabled: false
      cluster-local-gateway:
        autoscaleEnabled: false
        enabled: true
        labels:
          app: cluster-local-gateway
          istio: cluster-local-gateway
        ports:
          - name: status-port
            port: 15020
          - name: http2
            port: 80
            targetPort: 80
          - name: https
            port: 443
    grafana:
      enabled: false
    mixer:
      enabled: false
      policy:
        enabled: false
      telemetry:
        enabled: false
    pilot:
      autoscaleEnabled: false
      sidecar: false
    prometheus:
      enabled: false
    security:
      enabled: false
    sidecarInjectorWebhook:
      enabled: false
    kiali:
      enabled: false
    tracing:
      enabled: false
