apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: knative-serving-operator
  annotations:
    networkoperator.openshift.io/ignore-errors: ""
  name: knative-serving-operator
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector: {}
  selector:
    matchLabels:
      name: knative-serving-operator
